### PR TITLE
Add new EID object attributes to IAB schema

### PR DESCRIPTION
**Pull request by Symbols-max**

### CODE REVIEW

**Review by dmytro-babichev — CHANGES_REQUESTED** [review]
don't you need this PR to point to a commit in AdCom lib?

**Comment by Symbols-max** [comment]
> don't you need this PR to point to a commit in AdCom lib?

I plan to modify after merge [https://github.com/IABTechLab/adcom-proto/pull/20](https://github.com/IABTechLab/adcom-proto/pull/20)

**Review by dmytro-babichev — APPROVED** [review]

**Comment by dmytro-babichev** [comment]
@simontrasler could you take a look?

**Review by reshmin — APPROVED** [review]

**Review by simontrasler — APPROVED** [review]

**Comment by Symbols-max** [comment]
@simontrasler Could you please release new tag?

**Pull request merged**
