### PR TITLE
Update to support OpenRTB 2.6

### PR DESCRIPTION
**Pull request by Youri-Sdobnikov**
https://iabtechlab.com/wp-content/uploads/2022/04/OpenRTB-2-6_FINAL.pdf

### CODE REVIEW

**Review by simontrasler — CHANGES_REQUESTED** [review]
Need to revert the changes from `bool` to `int32`.

**Comment by Youri-Sdobnikov** [comment]
> Need to revert the changes from bool to int32.

@simontrasler done

**Comment by gouyelliot** [comment]
I can't find the new field `plcmt` on Video, both field `placement` and `plcmt` should be present to ensure backward compatibility between 2.5 and 2.6, as detailed [here](https://iabtechlab.com/blog/march-2023-update-to-openrtb-is-now-ready-for-implementation/):
> There will be a new field called “plcmt” that will contain the new values and can exist in tandem with the legacy “placement” during an ample migration period.

**Comment by simontrasler** [comment]
Heads-up, I am closing this pull request and we'll be adding the changes in smaller (feature-oriented) pull requests. And noted, `plcmt` will be included in those.

**Pull request closed without merging**
