### PR TITLE
Backport connection type for 5G from AdCOM 1.0 [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by simontrasler**

### CODE REVIEW

**Comment by JoelPM** [comment]
Looks good to me. As Ian noted, not technically in the spec, but there may be value in adding/reserving it anyway since it is defined in AdCOM.

**Comment by simontrasler** [comment]
I am talking to @amitshetty about whether we should formally add this and other new enum values from OpenRTB 3.0 to OpenRTB 2.5. The specification must be updated first -- this repository will reflect that.

**Review by sergioserra-dev — APPROVED** [review]
Looks good.

**Review by sergioserra-dev — APPROVED** [review]

**Comment by simontrasler** [comment]
Not required. We have converted this field type to `int32` and moved the enum definitions to AdCOM.

**Pull request closed without merging**
